// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This file was auto-generated by Matlab under the supervision of Jacob Krucinski on 27-Mar-2017 at 22:43
#define Hmin      64.3103
#define Hmax      79.8404
#define Smin     223.5396
#define Smax     255.0000
#define Vmin     118.0000
#define Vmax     239.0000
#define MinHeight      30.0000
#define MinWidth       8.0000
#define MinRatio       0.1000
#define MaxRatio       0.5000
