// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This file was auto-generated by Matlab under the supervision of Jacob Krucinski on 25-Mar-2017 at 14:13
#define Hmin      64.3103
#define Hmax      79.8404
#define Smin     228.5396
#define Smax     255.0000
#define Lmin      47.5098
#define Lmax      95.0980
#define MinHeight      26.0000
#define MinWidth       5.0000
