// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This file was auto-generated by Matlab under the supervision of Jacob Krucinski on 02-Apr-2017 at 15:46
#define Hmin      67.4658
#define Hmax      88.2308
#define Smin     181.5236
#define Smax     255.0000
#define Vmin     211.0000
#define Vmax     255.0000
#define MinHeight      10.0000
#define MinWidth       5.0000
#define MinRatio       0.1000
#define MaxRatio       0.5000
