// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This file was auto-generated by Matlab under the supervision of Jacob Krucinski on 31-Mar-2017 at 21:47
#define Hmin      67.4658
#define Hmax      88.2308
#define Smin     183.0000
#define Smax     255.0000
#define Vmin     221.0000
#define Vmax     255.0000
#define MinHeight      45.0000
#define MinWidth      14.0000
#define MinRatio       0.1000
#define MaxRatio       0.5000
